@file:Suppress("INACCESSIBLE_TYPE")

plugins {
    id("org.openrndr.convention.kotlin-multiplatform")
    id("org.openrndr.convention.kotlin-multiplatform-js")
}

abstract class TransformDemosTask : DefaultTask() {
    @get:InputDirectory
    abstract val inputDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputJsDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputResourcesDir: DirectoryProperty

    @TaskAction
    fun transformJs() {

        data class ApplicationEntry(val title: String, val functionName: String)
        val applications = mutableListOf<ApplicationEntry>()

        val out = outputJsDir.get().asFile.apply { deleteRecursively(); mkdirs() }
        inputDir.get().asFile.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .forEach { file ->
                val name = file.nameWithoutExtension
                val transformed = file.readText()
                    .replace(Regex("""fun\s+main\s*\("""), "fun entry_$name(")
                out.resolve(file.name).writeText(transformed)
                applications.add(ApplicationEntry(name, "$name"))
            }

        val listItems = applications.joinToString("\n") { application ->
            "            <li><button class=\"application-button\" data-application=\"${application.functionName}\">${application.title}</button></li>"
        }

        val html = """
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <title>openrndr-webgl-demo</title>
                <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
                <style>
                    body, html {
                        margin: 0;
                        width: 100%;
                        height: 100%;
                        overflow: hidden;
                        font-family: sans-serif;
                    }
                    #openrndr-canvas {
                        display: block;
                        width: 100%;
                        height: 100%;
                    }
                    #application-list {
                        position: absolute;
                        top: 0;
                        left: 0;
                        z-index: 1;
                        background: rgba(255, 255, 255, 0.85);
                        padding: 8px;
                        margin: 0;
                        list-style: none;
                    }
                    .application-button {
                        display: block;
                        width: 100%;
                        margin: 2px 0;
                    }
                </style>
            </head>
            <body>
            <ul id="application-list">
${listItems}
            </ul>
            <canvas id="openrndr-canvas"></canvas>
            <script src="openrndr-program.js"></script>
            <script>
                document.querySelectorAll(".application-button").forEach(function (button) {
                    button.addEventListener("click", function () {
                        var url = new URL(window.location.href);
                        url.searchParams.set("application", button.getAttribute("data-application"));
                        window.location.href = url.toString();
                    });
                });
            </script>
            </body>
            </html>
        """.trimIndent()

        val resourcesOutputDir = outputResourcesDir.get().asFile
        resourcesOutputDir.mkdirs()
        resourcesOutputDir.resolve("index.html").writeText(html + "\n")

        val whenBranches = applications.joinToString("\n") { application ->
            "                \"${application.functionName}\" -> entry_${application.functionName}()"
        }
        val defaultApplication = applications.firstOrNull()?.functionName

        val kotlinSource = """
            // Generated by the transformDemos task. Do not edit manually.
            import org.openrndr.ApplicationBuilder

            /**
             * The names of all applications found in the `src/commonDemo/kotlin` directory.
             */
            val availableApplications: List<String> = listOf(${applications.joinToString(", ") { "\"${it.functionName}\"" }})

            /**
             * Runs the application identified by [name], falling back to the first available application
             * when [name] is `null` or unknown.
             */
            fun runApplication(name: String?) {
                when (name) {
${whenBranches}
                    else -> entry_${defaultApplication?.let { "$it()" } ?: "error(\"no applications were found\")"}
                }
            }
        """.trimIndent()

        val outputFile = outputJsDir.get().asFile
        outputFile.mkdirs()
        outputFile.resolve("GeneratedApplications.kt").writeText(kotlinSource + "\n")
    }
}

val transformDemos = tasks.register<TransformDemosTask>("transformDemos") {
    inputDir.set(layout.projectDirectory.dir("src/commonDemo/kotlin"))
    outputJsDir.set(layout.buildDirectory.dir("generated/jsMain/kotlin"))
    outputResourcesDir.set(layout.buildDirectory.dir("generated/jsMain/resources"))
}

kotlin {
    js {
        browser {
            commonWebpackConfig {
                outputFileName = "openrndr-program.js"
                cssSupport {
                    enabled.set(true)
                }
            }
        }
        binaries.executable()
    }

    jvm {}

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(project(":openrndr-application"))
                implementation(project(":openrndr-draw"))
                implementation(libs.kotlin.coroutines)
            }
        }
        val commonDemo = create("commonDemo") {
            // Not connected to any actual js compilation: the sources of this
            // source set are only ever consumed after being rewritten by the
            // `transformDemos` task (see `jsMain`/`jvmMain` below), so it must
            // not be added to the compilation source set graph via `dependsOn`
            // from `jsMain`. It does, however, `dependsOn` `commonMain`
            // so that IntelliJ can resolve its dependencies and perform proper
            // source analysis on it.
            dependsOn(commonMain)
            kotlin.srcDir("src/commonDemo/kotlin")

            dependencies {
                implementation(project(":openrndr-application"))
                implementation(project(":openrndr-draw"))
                implementation(libs.kotlin.coroutines)
            }
        }

        getByName("jsMain") {
            kotlin.srcDir(transformDemos.map { it.outputJsDir })
            resources.srcDir(transformDemos.map { it.outputResourcesDir })
            dependencies {
                implementation(project(":openrndr-gl-common"))
                implementation(project(":openrndr-js:openrndr-webgl"))
            }
        }

        getByName("jvmMain") {
            // By depending on commonDemo we allow IntelliJ to run applications as JVM applications
            dependsOn(commonDemo)
            dependencies {
                runtimeOnly(project(":openrndr-jvm:openrndr-application-glfw"))
                runtimeOnly(libs.slf4j.simple)
            }
        }
    }
}

// Ensure that demo sources are transformed before they are compiled or processed.
// The transformDemos task rewrites demo entry points and generates the program index,
// which must complete before Kotlin/JS compilation and resource processing begin.
tasks.named("compileKotlinJs") {
    dependsOn(transformDemos)
}

// The jsProcessResources task must wait for transformDemos to complete because it generates
// the index.html file that needs to be included in the processed resources.
tasks.named("jsProcessResources") {
    dependsOn(transformDemos)
}