name: Release API docs
on:
  push:
    branches:
      - master

jobs:
  release_apidocs:
    if: github.repository == 'openrndr/openrndr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build apidocs
        run: ./gradlew dokkaHtmlMultiModule -Dorg.gradle.jvmargs=-Xmx1536M

      - name: Publish to gh-pages
        run: |
          git worktree add --detach docs-temp
          cd docs-temp
          git checkout --orphan gh-pages
          git reset HEAD -- .
          git clean -df
          mv ../build/dokka/htmlMultiModule/* .
          echo api.openrndr.org > CNAME
          git status
          git config --global user.email "actions@openrndr.org"
          git config --global user.name "OPENRNDR Actions"
          git add . 
          git commit -m "Add automatically generated API docs"
          git push origin gh-pages --force